package coeusyk.game.chess.core.selfplay.vspr;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.zip.CRC32;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Cross-language contract verification for #211: every fixture under {@code fixtures/vspr/} is
 * the independent oracle -- these bytes were extracted directly from DR-220's own committed hex
 * blocks, not generated by this codec (see {@code fixtures/vspr/MANIFEST.md}). This suite never
 * regenerates an expected hash from {@link VsprCodec}; every expected SHA-256 below is hardcoded
 * from the manifest, independently of whatever the codec under test produces.
 */
class VsprCodecTest {

    private static final Path FIXTURES = RepoPaths.repoRoot().resolve("fixtures/vspr");
    private static final int HEADER_LEN = 120;
    private static final int FRAME_BODY_START = HEADER_LEN + 4;

    // ---- Common header field expectations, shared by every canonical fixture ----
    private static final byte[] RUN_ID =
            hex("0000000000000000000000000000AAAA");
    private static final byte[] NETWORK_SHA256 =
            hex("000000000000000000000000000000000000000000000000000000000000BEEF");

    // =====================================================================================
    // Valid fixtures: decode successfully, assert exact semantics, re-encode byte-for-byte
    // =====================================================================================

    @Test
    void validOrdinaryCpSample_decodesExactSemanticsAndReEncodesToCanonicalBytes()
            throws Exception {
        byte[] canonical = fixtureBytes("valid_01_ordinary_cp_sample.vspr");
        assertSha256(canonical, "aa1f3c2c8db50d7ba38da13563e2155c24062a3a46874c9f2a407cf77661f055");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        assertCommonHeader(file.header());
        assertFalse(file.header().candidatesPersisted());

        assertEquals(1, file.frames().size());
        GameFrame frame = file.frames().get(0);
        assertEquals(1L, frame.gameId());
        assertTrue(frame.gameSeed().isEmpty());
        assertEquals(GameOutcome.BLACK_WIN, frame.gameOutcome());
        assertEquals(TerminationReason.CHECKMATE, frame.terminationReason());
        assertEquals(OutcomePerspective.WHITE, frame.outcomePerspective());
        assertFoolsMateMoves(frame.playedMoves());
        assertEquals(0, frame.candidateSets().size());

        assertEquals(1, frame.samples().size());
        TrainingSample sample = frame.samples().get(0);
        assertEquals(0L, sample.ply());
        assertEquals("rnbqkbnr/pppppppp/8/8/8/5P2/PPPPP1PP/RNBQKBNR b KQkq - 0 1", sample.fen());
        assertTrue(sample.onTrajectory());
        assertEquals(ScoreKind.CP, sample.evalScoreKind());
        assertEquals(35, sample.evalScore());
        assertEquals(SearchBudgetKind.DEPTH, sample.searchBudgetKind());
        assertEquals(6L, sample.searchBudgetValue());

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    @Test
    void validMateScoreSample_decodesExactSemantics() throws Exception {
        byte[] canonical = fixtureBytes("valid_02_mate_score_sample.vspr");
        assertSha256(canonical,
                "a7298f75fb56deb3776a8784228d58009e87067bb9277505c55523acf9b330b8");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        GameFrame frame = file.frames().get(0);
        assertEquals(2L, frame.gameId());
        assertEquals(GameOutcome.BLACK_WIN, frame.gameOutcome());
        assertEquals(TerminationReason.CHECKMATE, frame.terminationReason());
        assertFoolsMateMoves(frame.playedMoves());

        TrainingSample sample = frame.samples().get(0);
        assertEquals(2L, sample.ply());
        assertEquals("rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2",
                sample.fen());
        assertEquals(ScoreKind.MATE, sample.evalScoreKind());
        assertEquals(1, sample.evalScore());

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    @Test
    void validNaturalDraw_decodesExactSemantics() throws Exception {
        byte[] canonical = fixtureBytes("valid_03_natural_draw.vspr");
        assertSha256(canonical,
                "dcf84913117080e89a8650db617c29e20179c6b58b6f45310df7253d46b80bd9");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        GameFrame frame = file.frames().get(0);
        assertEquals(3L, frame.gameId());
        assertEquals(GameOutcome.DRAW, frame.gameOutcome());
        assertEquals(TerminationReason.THREEFOLD_REPETITION, frame.terminationReason());

        int[] expectedMoves = {0x0546, 0x0B7E, 0x0195, 0x0FAD, 0x0546, 0x0B7E, 0x0195, 0x0FAD};
        assertEquals(expectedMoves.length, frame.playedMoves().size());
        for (int i = 0; i < expectedMoves.length; i++) {
            assertEquals(expectedMoves[i], frame.playedMoves().get(i).move(), "move index " + i);
        }

        TrainingSample sample = frame.samples().get(0);
        assertEquals("rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R b KQkq - 1 1", sample.fen());
        assertEquals(10, sample.evalScore());

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    @Test
    void validInfrastructureUnresolved_decodesExactSemanticsWithZeroSamples() throws Exception {
        byte[] canonical = fixtureBytes("valid_04_infrastructure_unresolved.vspr");
        assertSha256(canonical,
                "e7b5d4245aa69a66acd5211de206f40cbd93b3bb9f26437a81d32036e739b01a");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        GameFrame frame = file.frames().get(0);
        assertEquals(4L, frame.gameId());
        assertEquals(GameOutcome.UNRESOLVED, frame.gameOutcome());
        assertEquals(TerminationReason.MOVE_CAP, frame.terminationReason());
        assertEquals(2, frame.playedMoves().size());
        assertEquals(0, frame.samples().size(), "zero-sample game must decode, not error");

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    @Test
    void validCandidateSectionPresent_decodesExactSemantics() throws Exception {
        byte[] canonical = fixtureBytes("valid_05_candidate_section_present.vspr");
        assertSha256(canonical,
                "194abdf017ef31cd89226044452757ed848a9671a60c5326571bb66be514cc8a");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        assertTrue(file.header().candidatesPersisted());

        GameFrame frame = file.frames().get(0);
        assertEquals(1, frame.candidateSets().size());
        CandidateSet set = frame.candidateSets().get(0);
        assertEquals(0L, set.ply());
        assertEquals(6, set.depth());
        assertEquals(1, set.candidates().size());
        SearchCandidate candidate = set.candidates().get(0);
        assertEquals(0x054D, candidate.move());
        assertEquals(0, candidate.rank());
        assertEquals(ScoreKind.CP, candidate.scoreKind());
        assertEquals(35, candidate.score());
        assertTrue(candidate.pv().isEmpty());
        assertTrue(candidate.complete());

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    @Test
    void validMaxLengthFen_decodesExactSemanticsAtTheBoundary() throws Exception {
        byte[] canonical = fixtureBytes("valid_06_max_length_fen.vspr");
        assertSha256(canonical,
                "0e27990b82172f41bdcb8f1cb5b4063ecf94d966fc30f60fac4d63193adbc08e");

        VsprFile file = VsprCodec.read(new ByteArrayInputStream(canonical));
        TrainingSample sample = file.frames().get(0).samples().get(0);
        assertEquals(100, sample.fen().getBytes(StandardCharsets.US_ASCII).length,
                "must decode a FEN at exactly the 100-byte bound, not reject it");

        assertRoundTripsToCanonicalBytes(file, canonical);
    }

    // =====================================================================================
    // Invalid fixtures: precise rejection category, no partially-valid object returned
    // =====================================================================================

    @Test
    void invalidTruncatedFrame_rejectsAsTruncated_evenAsTheOnlyFrame() throws Exception {
        byte[] bytes = fixtureBytes("invalid_07_truncated_frame.vspr");
        assertSha256(bytes, "1ed0421adf7e7bcf413da55423e1bb1f89f226cc9b22294589fd1d2ff60e4f9a");

        VsprFormatException ex = assertThrows(VsprFormatException.class,
                () -> VsprCodec.read(new ByteArrayInputStream(bytes)));
        assertEquals(VsprFormatException.Reason.TRUNCATED, ex.reason());
    }

    @Test
    void invalidUnsupportedFormatVersion_hardRejectsWholeFile() throws Exception {
        byte[] bytes = fixtureBytes("invalid_08_unsupported_format_version.vspr");
        assertSha256(bytes, "198728e0475801cd6a9611606077bd7b9440526d45556c64a530a78ce1a88664");

        VsprFormatException ex = assertThrows(VsprFormatException.class,
                () -> VsprCodec.read(new ByteArrayInputStream(bytes)));
        assertEquals(VsprFormatException.Reason.UNSUPPORTED_VERSION, ex.reason());
    }

    @Test
    void invalidEnumTag_rejectsUndefinedGameOutcome() throws Exception {
        byte[] bytes = fixtureBytes("invalid_09_invalid_enum_tag.vspr");
        assertSha256(bytes, "262676430c22a1cd4fad519d0282cd8449d85ad3dd88e3cf9d4d322fdefe0da3");

        VsprFormatException ex = assertThrows(VsprFormatException.class,
                () -> VsprCodec.read(new ByteArrayInputStream(bytes)));
        assertEquals(VsprFormatException.Reason.INVALID_ENUM, ex.reason());
    }

    // =====================================================================================
    // Synthetic in-memory mutations -- cheap decoder-branch coverage beyond the four canonical
    // invalid fixtures (task section 8); constructed here, never committed as files.
    // =====================================================================================

    @Test
    void badMagic_rejected() throws Exception {
        byte[] mutated = withByte(base(), 0, 0x00);
        assertReason(mutated, VsprFormatException.Reason.BAD_MAGIC);
    }

    @Test
    void crcMismatch_rejected() throws Exception {
        byte[] fixture = base();
        byte[] mutated = fixture.clone();
        mutated[mutated.length - 1] ^= 0x01; // flip one bit of the trailing CRC itself
        assertReason(mutated, VsprFormatException.Reason.CRC_MISMATCH);
    }

    @Test
    void oversizedFrameLength_rejectedBeforeAllocation() throws Exception {
        byte[] mutated = base().clone();
        mutated[HEADER_LEN] = (byte) 0xFF;
        mutated[HEADER_LEN + 1] = (byte) 0xFF;
        mutated[HEADER_LEN + 2] = (byte) 0xFF;
        mutated[HEADER_LEN + 3] = (byte) 0xFF;
        assertReason(mutated, VsprFormatException.Reason.BOUND_VIOLATION);
    }

    @Test
    void invalidBoolByte_rejected() throws Exception {
        byte[] mutated = recomputeCrc(withByte(base(), 116, 2)); // resetSearchStateBetweenGames
        VsprFormatException ex = assertThrows(VsprFormatException.class,
                () -> VsprCodec.readHeader(new java.io.DataInputStream(
                        new ByteArrayInputStream(mutated))));
        assertEquals(VsprFormatException.Reason.INVALID_ENUM, ex.reason());
    }

    @Test
    void invalidMoveFlagNibble_rejected() throws Exception {
        // Byte 140 is the high byte of the first PlayedMoveDecision's packed move (0x054D);
        // setting its top nibble to 9 makes flag=9, outside the valid 0-8 range.
        byte[] mutated = recomputeCrc(withByte(base(), 140, 0x95));
        assertReason(mutated, VsprFormatException.Reason.INVALID_ENUM);
    }

    @Test
    void invalidScoreKind_rejected() throws Exception {
        byte[] mutated = recomputeCrc(withByte(base(), 224, 2)); // evalScoreKind
        assertReason(mutated, VsprFormatException.Reason.INVALID_ENUM);
    }

    @Test
    void invalidOutcomeTerminationPairing_rejected() throws Exception {
        // gameOutcome=DRAW(2) paired with terminationReason=CHECKMATE(0, unchanged) is invalid.
        byte[] mutated = recomputeCrc(withByte(base(), 133, 2));
        assertReason(mutated, VsprFormatException.Reason.INVALID_PAIRING);
    }

    @Test
    void fenOverMaxLength_rejectedBeforeAllocation() throws Exception {
        byte[] mutated = recomputeCrc(withByte(base(), 164, 150)); // fen bstr8 length byte
        assertReason(mutated, VsprFormatException.Reason.BOUND_VIOLATION);
    }

    @Test
    void nonAsciiFen_rejected() throws Exception {
        byte[] mutated = recomputeCrc(withByte(base(), 165, 0xFF)); // first FEN byte
        assertReason(mutated, VsprFormatException.Reason.STRUCTURAL);
    }

    @Test
    void samplePlyOutOfRange_rejected() throws Exception {
        // sample.ply bytes at [160:164]; playedMoveCount is 4, so ply=4 is out of range.
        byte[] fixture = base().clone();
        fixture[163] = 0x04;
        byte[] mutated = recomputeCrc(fixture);
        assertReason(mutated, VsprFormatException.Reason.STRUCTURAL);
    }

    @Test
    void candidateCountOverBound_rejectedBeforeAllocation() throws Exception {
        byte[] fixture = fixtureBytes("valid_05_candidate_section_present.vspr").clone();
        fixture[250] = (byte) 0x00;
        fixture[251] = (byte) 0xFF; // candidateCount = 255 > 218
        byte[] mutated = recomputeCrc(fixture);
        assertReason(mutated, VsprFormatException.Reason.BOUND_VIOLATION);
    }

    @Test
    void pvLengthOverBound_rejectedBeforeAllocation() throws Exception {
        byte[] fixture = fixtureBytes("valid_05_candidate_section_present.vspr").clone();
        fixture[261] = (byte) 0x00;
        fixture[262] = (byte) 0xFF; // pvLength = 255 > 128
        byte[] mutated = recomputeCrc(fixture);
        assertReason(mutated, VsprFormatException.Reason.BOUND_VIOLATION);
    }

    // =====================================================================================
    // Helpers
    // =====================================================================================

    private static void assertFoolsMateMoves(List<PlayedMoveDecision> moves) {
        int[] expected = {0x054D, 0x0934, 0x078E, 0x07FB};
        assertEquals(expected.length, moves.size());
        for (int i = 0; i < expected.length; i++) {
            assertEquals(expected[i], moves.get(i).move(), "move index " + i);
            assertEquals(SelectionMechanismKind.BEST_MOVE, moves.get(i).selectionMechanismKind());
            assertTrue(moves.get(i).selectionSeed().isEmpty());
        }
    }

    private static void assertCommonHeader(VsprHeader h) {
        assertEquals(1, h.formatVersion());
        assertArrayEquals(RUN_ID, h.runId());
        assertEquals(1_700_000_000L, h.createdAtEpochSeconds());
        assertEquals("fixture-net-0001", h.generatorNetworkUuid());
        assertArrayEquals(NETWORK_SHA256, h.generatorNetworkSha256());
        assertEquals("fixture-build-0001", h.engineBuildId());
        assertEquals("", h.generatorNetworkPath());
        assertEquals(500, h.maxPlies());
        assertEquals(SearchBudgetKind.DEPTH, h.searchBudgetKind());
        assertEquals(6L, h.searchBudgetValue());
        assertTrue(h.resetSearchStateBetweenGames());
        assertEquals(null, h.adjudicationConfig());
        assertEquals(null, h.diversityConfig());
    }

    private static void assertRoundTripsToCanonicalBytes(VsprFile file, byte[] canonical)
            throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        VsprCodec.write(file, out);
        assertArrayEquals(canonical, out.toByteArray(),
                "encoding the decoded semantic object must reproduce the canonical bytes exactly");
    }

    private static void assertReason(byte[] bytes, VsprFormatException.Reason expected) {
        VsprFormatException ex = assertThrows(VsprFormatException.class,
                () -> VsprCodec.read(new ByteArrayInputStream(bytes)));
        assertEquals(expected, ex.reason());
    }

    private static byte[] base() throws IOException {
        return fixtureBytes("valid_01_ordinary_cp_sample.vspr");
    }

    private static byte[] withByte(byte[] original, int offset, int value) {
        byte[] copy = original.clone();
        copy[offset] = (byte) value;
        return copy;
    }

    /** Recomputes and patches the trailing CRC-32 after an in-body mutation, so the test
     * actually exercises the intended validation branch instead of being masked by an
     * incidental CRC mismatch (frameLength itself is assumed unchanged by the mutation). */
    private static byte[] recomputeCrc(byte[] fixture) {
        byte[] copy = fixture.clone();
        long frameLength = readU32BE(copy, HEADER_LEN);
        int bodyEnd = (int) (FRAME_BODY_START + frameLength);
        CRC32 crc = new CRC32();
        crc.update(copy, FRAME_BODY_START, (int) frameLength);
        writeU32BE(copy, bodyEnd, crc.getValue());
        return copy;
    }

    private static long readU32BE(byte[] b, int offset) {
        return ((long) (b[offset] & 0xFF) << 24) | ((b[offset + 1] & 0xFF) << 16)
                | ((b[offset + 2] & 0xFF) << 8) | (b[offset + 3] & 0xFF);
    }

    private static void writeU32BE(byte[] b, int offset, long value) {
        b[offset] = (byte) (value >>> 24);
        b[offset + 1] = (byte) (value >>> 16);
        b[offset + 2] = (byte) (value >>> 8);
        b[offset + 3] = (byte) value;
    }

    private static byte[] fixtureBytes(String filename) throws IOException {
        return Files.readAllBytes(FIXTURES.resolve(filename));
    }

    private static void assertSha256(byte[] bytes, String expectedHex) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(bytes);
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            assertEquals(expectedHex, sb.toString(),
                    "fixture bytes on disk no longer match the manifest's committed SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    private static byte[] hex(String s) {
        int len = s.length();
        byte[] out = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            out[i / 2] = (byte) Integer.parseInt(s.substring(i, i + 2), 16);
        }
        return out;
    }
}
