"""Cross-language contract verification for #211 -- Python half. Every fixture under
fixtures/vspr/ is the independent oracle (see fixtures/vspr/MANIFEST.md and the Java suite,
engine-core/src/test/java/.../selfplay/vspr/VsprCodecTest.java): these bytes were extracted
directly from DR-220's own committed hex blocks, not generated by this decoder. Every expected
SHA-256 below is hardcoded from the manifest, independently of whatever this decoder produces --
this suite never regenerates an expected hash from the code under test.
"""

import hashlib
from pathlib import Path

import pytest

from trainer.encoding.feature_spec import repo_root
from trainer.vspr import (
    BAD_MAGIC,
    BOUND_VIOLATION,
    CRC_MISMATCH,
    INVALID_ENUM,
    INVALID_PAIRING,
    STRUCTURAL,
    TRUNCATED,
    UNSUPPORTED_VERSION,
    GameOutcome,
    ScoreKind,
    SearchBudgetKind,
    SelectionMechanismKind,
    TerminationReason,
    VsprFormatError,
    read,
)

FIXTURES = repo_root(Path(__file__).resolve()) / "fixtures" / "vspr"

RUN_ID = bytes.fromhex("0000000000000000000000000000aaaa")
NETWORK_SHA256 = bytes.fromhex(
    "000000000000000000000000000000000000000000000000000000000000beef"
)

HEADER_LEN = 120
FRAME_BODY_START = HEADER_LEN + 4


def _fixture_bytes(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def _assert_sha256(data: bytes, expected_hex: str) -> None:
    assert hashlib.sha256(data).hexdigest() == expected_hex


def _with_byte(data: bytes, offset: int, value: int) -> bytearray:
    mutated = bytearray(data)
    mutated[offset] = value
    return mutated


def _recompute_crc(data: bytearray) -> bytes:
    import struct
    import zlib

    mutated = bytearray(data)
    frame_length = struct.unpack(">I", bytes(mutated[HEADER_LEN:HEADER_LEN + 4]))[0]
    body_end = FRAME_BODY_START + frame_length
    crc = zlib.crc32(bytes(mutated[FRAME_BODY_START:body_end])) & 0xFFFFFFFF
    mutated[body_end:body_end + 4] = struct.pack(">I", crc)
    return bytes(mutated)


def _base() -> bytes:
    return _fixture_bytes("valid_01_ordinary_cp_sample.vspr")


def _assert_reason(data: bytes, expected_reason: str) -> None:
    with pytest.raises(VsprFormatError) as excinfo:
        read(data)
    assert excinfo.value.reason == expected_reason


def _assert_common_header(header) -> None:
    assert header.format_version == 1
    assert header.run_id == RUN_ID
    assert header.created_at_epoch_seconds == 1_700_000_000
    assert header.generator_network_uuid == "fixture-net-0001"
    assert header.generator_network_sha256 == NETWORK_SHA256
    assert header.engine_build_id == "fixture-build-0001"
    assert header.generator_network_path == ""
    assert header.max_plies == 500
    assert header.search_budget_kind == SearchBudgetKind.DEPTH
    assert header.search_budget_value == 6
    assert header.reset_search_state_between_games is True
    assert header.adjudication_config is None
    assert header.diversity_config is None


def _assert_fools_mate_moves(moves) -> None:
    expected = [0x054D, 0x0934, 0x078E, 0x07FB]
    assert [m.move for m in moves] == expected
    for m in moves:
        assert m.selection_mechanism_kind == SelectionMechanismKind.BEST_MOVE
        assert m.selection_seed is None


# =====================================================================================
# Valid fixtures
# =====================================================================================


def test_valid_ordinary_cp_sample_decodes_exact_semantics():
    data = _base()
    _assert_sha256(data, "aa1f3c2c8db50d7ba38da13563e2155c24062a3a46874c9f2a407cf77661f055")

    file = read(data)
    _assert_common_header(file.header)
    assert file.header.candidates_persisted is False

    assert len(file.frames) == 1
    frame = file.frames[0]
    assert frame.game_id == 1
    assert frame.game_seed is None
    assert frame.game_outcome == GameOutcome.BLACK_WIN
    assert frame.termination_reason == TerminationReason.CHECKMATE
    _assert_fools_mate_moves(frame.played_moves)
    assert frame.candidate_sets == []

    assert len(frame.samples) == 1
    sample = frame.samples[0]
    assert sample.ply == 0
    assert sample.fen == "rnbqkbnr/pppppppp/8/8/8/5P2/PPPPP1PP/RNBQKBNR b KQkq - 0 1"
    assert sample.on_trajectory is True
    assert sample.eval_score_kind == ScoreKind.CP
    assert sample.eval_score == 35
    assert sample.search_budget_kind == SearchBudgetKind.DEPTH
    assert sample.search_budget_value == 6


def test_valid_mate_score_sample_decodes_exact_semantics():
    data = _fixture_bytes("valid_02_mate_score_sample.vspr")
    _assert_sha256(data, "a7298f75fb56deb3776a8784228d58009e87067bb9277505c55523acf9b330b8")

    file = read(data)
    frame = file.frames[0]
    assert frame.game_id == 2
    _assert_fools_mate_moves(frame.played_moves)

    sample = frame.samples[0]
    assert sample.ply == 2
    assert sample.fen == "rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2"
    assert sample.eval_score_kind == ScoreKind.MATE
    assert sample.eval_score == 1


def test_valid_natural_draw_decodes_exact_semantics():
    data = _fixture_bytes("valid_03_natural_draw.vspr")
    _assert_sha256(data, "dcf84913117080e89a8650db617c29e20179c6b58b6f45310df7253d46b80bd9")

    file = read(data)
    frame = file.frames[0]
    assert frame.game_id == 3
    assert frame.game_outcome == GameOutcome.DRAW
    assert frame.termination_reason == TerminationReason.THREEFOLD_REPETITION

    expected_moves = [0x0546, 0x0B7E, 0x0195, 0x0FAD, 0x0546, 0x0B7E, 0x0195, 0x0FAD]
    assert [m.move for m in frame.played_moves] == expected_moves

    sample = frame.samples[0]
    assert sample.fen == "rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R b KQkq - 1 1"
    assert sample.eval_score == 10


def test_valid_infrastructure_unresolved_decodes_with_zero_samples():
    data = _fixture_bytes("valid_04_infrastructure_unresolved.vspr")
    _assert_sha256(data, "e7b5d4245aa69a66acd5211de206f40cbd93b3bb9f26437a81d32036e739b01a")

    file = read(data)
    frame = file.frames[0]
    assert frame.game_id == 4
    assert frame.game_outcome == GameOutcome.UNRESOLVED
    assert frame.termination_reason == TerminationReason.MOVE_CAP
    assert len(frame.played_moves) == 2
    assert frame.samples == []


def test_valid_candidate_section_present_decodes_exact_semantics():
    data = _fixture_bytes("valid_05_candidate_section_present.vspr")
    _assert_sha256(data, "194abdf017ef31cd89226044452757ed848a9671a60c5326571bb66be514cc8a")

    file = read(data)
    assert file.header.candidates_persisted is True

    frame = file.frames[0]
    assert len(frame.candidate_sets) == 1
    cset = frame.candidate_sets[0]
    assert cset.ply == 0
    assert cset.depth == 6
    assert len(cset.candidates) == 1
    candidate = cset.candidates[0]
    assert candidate.move == 0x054D
    assert candidate.rank == 0
    assert candidate.score_kind == ScoreKind.CP
    assert candidate.score == 35
    assert candidate.pv == []
    assert candidate.complete is True


def test_valid_max_length_fen_decodes_at_the_boundary():
    data = _fixture_bytes("valid_06_max_length_fen.vspr")
    _assert_sha256(data, "0e27990b82172f41bdcb8f1cb5b4063ecf94d966fc30f60fac4d63193adbc08e")

    file = read(data)
    sample = file.frames[0].samples[0]
    assert len(sample.fen.encode("ascii")) == 100


# =====================================================================================
# Invalid fixtures -- clean rejection, precise reason, no partially-valid object returned
# =====================================================================================


def test_invalid_truncated_frame_rejects_even_as_the_only_frame():
    data = _fixture_bytes("invalid_07_truncated_frame.vspr")
    _assert_sha256(data, "1ed0421adf7e7bcf413da55423e1bb1f89f226cc9b22294589fd1d2ff60e4f9a")
    _assert_reason(data, TRUNCATED)


def test_invalid_unsupported_format_version_hard_rejects_whole_file():
    data = _fixture_bytes("invalid_08_unsupported_format_version.vspr")
    _assert_sha256(data, "198728e0475801cd6a9611606077bd7b9440526d45556c64a530a78ce1a88664")
    _assert_reason(data, UNSUPPORTED_VERSION)


def test_invalid_enum_tag_rejects_undefined_game_outcome():
    data = _fixture_bytes("invalid_09_invalid_enum_tag.vspr")
    _assert_sha256(data, "262676430c22a1cd4fad519d0282cd8449d85ad3dd88e3cf9d4d322fdefe0da3")
    _assert_reason(data, INVALID_ENUM)


# =====================================================================================
# Synthetic in-memory mutations -- same decoder-branch coverage as the Java suite
# =====================================================================================


def test_bad_magic_rejected():
    _assert_reason(bytes(_with_byte(_base(), 0, 0x00)), BAD_MAGIC)


def test_crc_mismatch_rejected():
    mutated = bytearray(_base())
    mutated[-1] ^= 0x01
    _assert_reason(bytes(mutated), CRC_MISMATCH)


def test_oversized_frame_length_rejected_before_allocation():
    mutated = bytearray(_base())
    mutated[HEADER_LEN:HEADER_LEN + 4] = b"\xff\xff\xff\xff"
    _assert_reason(bytes(mutated), BOUND_VIOLATION)


def test_invalid_bool_byte_rejected():
    mutated = _recompute_crc(_with_byte(_base(), 116, 2))
    _assert_reason(mutated, INVALID_ENUM)


def test_invalid_move_flag_nibble_rejected():
    mutated = _recompute_crc(_with_byte(_base(), 140, 0x95))
    _assert_reason(mutated, INVALID_ENUM)


def test_invalid_score_kind_rejected():
    mutated = _recompute_crc(_with_byte(_base(), 224, 2))
    _assert_reason(mutated, INVALID_ENUM)


def test_invalid_outcome_termination_pairing_rejected():
    mutated = _recompute_crc(_with_byte(_base(), 133, 2))
    _assert_reason(mutated, INVALID_PAIRING)


def test_fen_over_max_length_rejected_before_allocation():
    mutated = _recompute_crc(_with_byte(_base(), 164, 150))
    _assert_reason(mutated, BOUND_VIOLATION)


def test_non_ascii_fen_rejected():
    mutated = _recompute_crc(_with_byte(_base(), 165, 0xFF))
    _assert_reason(mutated, STRUCTURAL)


def test_sample_ply_out_of_range_rejected():
    mutated = bytearray(_base())
    mutated[163] = 0x04
    _assert_reason(_recompute_crc(mutated), STRUCTURAL)


def test_candidate_count_over_bound_rejected_before_allocation():
    mutated = bytearray(_fixture_bytes("valid_05_candidate_section_present.vspr"))
    mutated[250:252] = b"\x00\xff"
    _assert_reason(_recompute_crc(mutated), BOUND_VIOLATION)


def test_pv_length_over_bound_rejected_before_allocation():
    mutated = bytearray(_fixture_bytes("valid_05_candidate_section_present.vspr"))
    mutated[261:263] = b"\x00\xff"
    _assert_reason(_recompute_crc(mutated), BOUND_VIOLATION)
