#!/usr/bin/env python3
"""Generate a Network Release Report (NNUE_PRD.md Sec.4 "Network Release Reports",
issue #205/E-5) from a network's provenance manifest, its already-recorded
validation numbers, and its gauntlet/SPRT match logs. Reuses the manifest as the
single source of truth for identity/architecture/data/training fields rather than
re-deriving or re-typing them -- the same "generated by script, not hand-written"
discipline docs/architecture/graph-audits/generate_report.py already established
for graph audits.

Usage:
    python3 generate_release_report.py \
        --manifest ../nets/dfffd3da-7f8f-4fc9-92dc-b3873c97fb21.json \
        --held-out-loss 0.08225942403078079 \
        --label-correlation 0.5043603181838989 \
        --held-out-count 4000 \
        --eval-scale-error-cp 735.5965576171875 \
        --eval-scale-count 393 \
        --train-count 36000 \
        --engine-commit 918bfc5 \
        --gauntlet-log ../tools/results/gauntlet_nnue_20260715_192136.log \
        --sprt-log ../tools/results/sprt_nnue-e5_<ts>.log \
        --out ../nets/dfffd3da-7f8f-4fc9-92dc-b3873c97fb21-release-report.md

ponytail: held-out-loss/label-correlation/eval-scale-error-cp are passed as flags
rather than parsed out of trainer/configs/train-e3-real.md's prose -- writing a
markdown parser for one already-human-readable document is not worth it for a
single existing net; add real parsing if/when a second net's report needs the
same numbers pulled from a differently-shaped source.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def load_manifest(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def extract_summary(log_path: Path | None) -> str:
    """Pull the final 'Score of ...' + 'Elo difference ...' lines straight out of
    the raw cutechess-cli log, rather than re-typing numbers by hand -- avoids a
    transcription mismatch between the report and the log it claims to summarize.
    cutechess-cli reprints a running 'Score of' line after every single game, so
    only the *last* one (the final tally) is kept -- not every intermediate line."""
    if log_path is None:
        return "_Not yet run._"
    text = log_path.read_text(encoding="utf-8")
    score_lines = [line.strip() for line in text.splitlines() if line.startswith("Score of")]
    tail_lines = [
        line.strip()
        for line in text.splitlines()
        if line.startswith("Elo difference") or re.match(r"^(H0|H1) accepted", line.strip())
    ]
    lines = ([score_lines[-1]] if score_lines else []) + tail_lines
    return "\n".join(lines) if lines else "_Log present but no summary lines found._"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--manifest", required=True, type=Path)
    p.add_argument("--held-out-loss", required=True, type=float)
    p.add_argument("--label-correlation", required=True, type=float)
    p.add_argument("--held-out-count", required=True, type=int,
                    help="Position count behind held-out-loss/label-correlation (PRD Sec.4 'position counts after filtering').")
    p.add_argument("--eval-scale-error-cp", required=True, type=float)
    p.add_argument("--eval-scale-count", required=True, type=int,
                    help="Position count behind eval-scale-error-cp.")
    p.add_argument("--train-count", required=True, type=int,
                    help="Training-set position count after filtering/split.")
    p.add_argument("--engine-commit", required=True)
    p.add_argument("--gauntlet-log", type=Path, default=None)
    p.add_argument("--sprt-log", type=Path, default=None)
    p.add_argument("--sprt-command", default=None,
                    help="Exact sprt invocation to record when --sprt-log is not yet available.")
    p.add_argument("--out", required=True, type=Path)
    args = p.parse_args()

    m = load_manifest(args.manifest)
    gauntlet_summary = extract_summary(args.gauntlet_log)
    sprt_summary = extract_summary(args.sprt_log)

    verdict = "Pending" if args.sprt_log is None else "See SPRT result above"

    dataset_lines = "\n".join(
        f"  - `{d['identifier']}` ({d['stage']}): {d['proportion']:.4%}" for d in m["dataset_composition"]
    )
    sprt_command_block = ""
    if args.sprt_command and args.sprt_log is None:
        sprt_command_block = (
            "Exact command to run on native Windows (per CLAUDE.md Sec.5 -- never simulated):\n\n"
            f"```\n{args.sprt_command}\n```"
        )

    report = f"""# Network Release Report — `{m['network_uuid']}`

Generated by `trainer/scripts/generate_release_report.py` (PRD Sec.4: "generated by
script, not hand-written"). Do not hand-edit; regenerate from the manifest and logs
instead.

## Identity

- **Network UUID:** `{m['network_uuid']}`
- **Network version/name:** N/A — the manifest schema has no separate version/name field beyond `network_uuid` (see `nets/{m['network_uuid']}.json`).
- **Created:** epoch {m['created_at_epoch_seconds']}
- **Trainer commit:** `{m['trainer_commit']}` (trainer version {m['trainer_version']})
- **Engine commit (tested against):** `{args.engine_commit}`
- **Manifest:** `nets/{m['network_uuid']}.json`

## Architecture

- **Feature set:** id {m['feature_set_id']}
- **Architecture id:** {m['architecture_id']}
- **Hidden width:** {m['hidden_width']}
- **Quantization:** qa={m['training_config']['qa']}, qb={m['training_config']['qb']}, output_scale={m['training_config']['output_scale']} (quant_version {m['quant_version']})

## Data

- **Dataset composition:**
{dataset_lines}
- **Position counts after filtering:** {args.train_count} training / {args.held_out_count} held-out / {args.eval_scale_count} classical-eval-scale corpus

## Training

- **Steps:** {m['training_config']['steps']}
- **Batch size:** {m['training_config']['batch_size']}
- **Learning rate:** {m['training_config']['learning_rate']}
- **K:** {m['training_config']['k']}
- **Seed:** {m['training_seed']}
- **Held-out loss:** {args.held_out_loss} (n={args.held_out_count})
- **Label correlation:** {args.label_correlation} (n={args.held_out_count})
- **Classical eval-scale error (mean abs diff, cp):** {args.eval_scale_error_cp} (n={args.eval_scale_count})

## Engine Results

### Gauntlet (E-4, #204)

```
{gauntlet_summary}
```

### SPRT (E-5, #205) — pinned terms H0=0, H1=+10, alpha=beta=0.05 (PRD Sec.1 gate 3)

```
{sprt_summary}
```
{sprt_command_block}

## Verdict

- **Correctness gate:** pass (perft/mirror-symmetry green throughout E-3/E-4, no engine-core changes since).
- **Performance gate:** deferred to E-6 (#206) per that issue's own scope — not measured or gated here.
- **Strength gate:** {verdict}
- **Promotion decision:** Pending — no decision recorded yet; the SPRT above is the input this decision requires, and issue #205's own Acceptance Criteria treat "not promoted yet" as an equally valid *recorded* outcome once the SPRT result is in. Not yet promoted, not yet rejected. See `nets/HISTORY.md` for the running ledger.

## Engineering Notes

- 2000 training steps against 36,000 positions is a deliberately small first real
  run (Track A's exit criterion is "a real net exists," not "a strong net exists").
  The 735.6cp classical-eval error and the 0-95-5 gauntlet loss are both consistent
  with an undertrained network, not a pipeline defect.
- Follow-up: a retraining cycle with more steps/data is expected before a future
  promotion attempt, per the roadmap's Track B framing.
"""
    args.out.write_text(report, encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
