"""Validator (NNUE_TRAINER_ARCHITECTURE.md Section 11 "Training level", PRD
"Evaluation Strategy" item 3, issue #197): held-out loss, label correlation, and
an eval-scale check against classical evaluation for a trained checkpoint.

`eval_scale_check()`'s input corpus is generated by the Java test-scope tool
`ClassicalCorpusGenerator` (`engine-core/src/test/java/.../eval/nnue/`, issue
#201) into `bench/nnue-corpus/classical-golden-evals.csv`; `load_classical_eval_corpus`
below reads that file.

Future work (documentation only -- not implemented, do not build ahead of a
real corpus to test against): once real trained checkpoints exist,
`eval_scale_check()` should grow beyond a single `mean_absolute_difference_cp`
scalar. Candidates: calibration metrics (e.g. a binned reliability curve of
predicted vs. classical eval, not just mean absolute difference, since a net
can have a low mean error while being systematically miscalibrated at the
tails); prediction distribution diagnostics (variance, skew, outlier rate
against classical eval, to catch a net that is well-centered on average but
wildly noisy per-position); and trend analysis across training runs (tracking
eval-scale drift checkpoint to checkpoint, so a regression is caught at the
run that introduced it instead of only at final validation). None of this is
buildable against the current hand-built fixture in a way that would be
meaningful -- it needs real trained checkpoints this module's scope boundary
above already defers.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

import torch

from trainer.contracts import PositionRecord
from trainer.model.batching import encode_batch, encode_fens
from trainer.model.network import NnueNet
from trainer.model.train import target_cp, texel_sigmoid


@dataclass(frozen=True)
class ValidationReport:
    held_out_loss: float
    label_correlation: float
    position_count: int


@dataclass(frozen=True)
class ClassicalEvalRecord:
    """One position with its classical-engine evaluation, in centipawns,
    side-to-move-relative (matching `PositionLabel.eval_cp`'s own convention)."""

    fen: str
    classical_eval_cp: int


def load_classical_eval_corpus(path: Path) -> List[ClassicalEvalRecord]:
    """Reads a `fen,eval` CSV produced by `ClassicalCorpusGenerator` (issue #201),
    skipping its leading `#`-prefixed regeneration-command comment and header row."""
    with open(path, newline="", encoding="ascii") as f:
        rows = [row for row in csv.reader(f) if row and not row[0].startswith("#")]
    if not rows or rows[0] != ["fen", "eval"]:
        raise ValueError(f"expected a 'fen,eval' header row, got {rows[0] if rows else 'an empty file'!r}")
    return [ClassicalEvalRecord(fen=row[0], classical_eval_cp=int(row[1])) for row in rows[1:]]


@dataclass(frozen=True)
class EvalScaleCheck:
    mean_absolute_difference_cp: float
    position_count: int


def evaluate_held_out(model: NnueNet, records: Iterable[PositionRecord], k: float) -> ValidationReport:
    """Held-out loss (the same texel-sigmoid MSE `train.py`'s training loop
    minimizes) and label correlation, over records the model was not trained on.
    """
    records = list(records)
    if not records:
        raise ValueError("evaluate_held_out requires at least one record")

    batch = encode_batch(records)
    target_cps = torch.tensor([target_cp(r.label) for r in records], dtype=torch.float32)
    targets = texel_sigmoid(target_cps, k)

    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)
        predicted_prob = texel_sigmoid(predicted_cp, k)
        loss = torch.mean((predicted_prob - targets) ** 2).item()
        correlation = _pearson_correlation(predicted_cp, target_cps)

    return ValidationReport(held_out_loss=loss, label_correlation=correlation, position_count=len(records))


def eval_scale_check(model: NnueNet, records: Iterable[ClassicalEvalRecord]) -> EvalScaleCheck:
    """Compares the trained net's raw centipawn output against a pre-computed
    classical-eval-labeled corpus (PRD "Trainer Requirements": the net's output
    must land on classical's calibrated centipawn scale, since search margins
    are tuned to that scale). See module docstring for the real corpus's status.
    """
    records = list(records)
    if not records:
        raise ValueError("eval_scale_check requires at least one record")

    batch = encode_fens(r.fen for r in records)
    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)

    classical_cps = torch.tensor([r.classical_eval_cp for r in records], dtype=torch.float32)
    mean_absolute_difference_cp = torch.mean(torch.abs(predicted_cp - classical_cps)).item()

    return EvalScaleCheck(
        mean_absolute_difference_cp=mean_absolute_difference_cp,
        position_count=len(records),
    )


def _pearson_correlation(a: torch.Tensor, b: torch.Tensor) -> float:
    a = a.detach()
    b = b.detach()
    a_centered = a - a.mean()
    b_centered = b - b.mean()
    denominator = torch.sqrt((a_centered**2).sum() * (b_centered**2).sum())
    if denominator == 0:
        return 0.0
    return ((a_centered * b_centered).sum() / denominator).item()
