"""Validator (NNUE_TRAINER_ARCHITECTURE.md Section 11 "Training level", PRD
"Evaluation Strategy" item 3, issue #197): held-out loss, label correlation, and
an eval-scale check against classical evaluation for a trained checkpoint.

`eval_scale_check()`'s input corpus is generated by the Java test-scope tool
`ClassicalCorpusGenerator` (`engine-core/src/test/java/.../eval/nnue/`, issue
#201) into `bench/nnue-corpus/classical-golden-evals.csv`; `load_classical_eval_corpus`
below reads that file.

Real trained checkpoints now exist (issue #219): `calibration_report()` below computes signed
mean error and score-compression ratio (`std(predicted)/std(target)`) against held-out
`target_cp` labels, split by mate/cp label and by phase -- the calibration-metrics candidate
this paragraph used to defer. It is a separate diagnostic from `eval_scale_check()`, which
compares against a classical-eval corpus rather than held-out labels; that one's remaining
candidates are still deferred future work, not yet needed: a binned reliability curve of
predicted vs. classical eval (mean error alone can hide tail miscalibration); prediction
distribution diagnostics (variance/skew/outlier rate against classical eval, to catch a net
that's well-centered on average but noisy per-position); and cross-checkpoint eval-scale drift
tracking.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

import torch

from trainer.contracts import PositionRecord
from trainer.dataset import phase_of
from trainer.model.batching import encode_batch, encode_fens
from trainer.model.network import NnueNet
from trainer.model.train import target_cp, texel_sigmoid


@dataclass(frozen=True)
class ValidationReport:
    held_out_loss: float
    label_correlation: float
    position_count: int


@dataclass(frozen=True)
class ClassicalEvalRecord:
    """One position with its classical-engine evaluation, in centipawns,
    side-to-move-relative (matching `PositionLabel.eval_cp`'s own convention)."""

    fen: str
    classical_eval_cp: int


def load_classical_eval_corpus(path: Path) -> List[ClassicalEvalRecord]:
    """Reads a `fen,eval` CSV produced by `ClassicalCorpusGenerator` (issue #201),
    skipping its leading `#`-prefixed regeneration-command comment and header row."""
    with open(path, newline="", encoding="ascii") as f:
        rows = [row for row in csv.reader(f) if row and not row[0].startswith("#")]
    if not rows or rows[0] != ["fen", "eval"]:
        raise ValueError(f"expected a 'fen,eval' header row, got {rows[0] if rows else 'an empty file'!r}")
    return [ClassicalEvalRecord(fen=row[0], classical_eval_cp=int(row[1])) for row in rows[1:]]


@dataclass(frozen=True)
class EvalScaleCheck:
    mean_absolute_difference_cp: float
    position_count: int


def evaluate_held_out(model: NnueNet, records: Iterable[PositionRecord], k: float) -> ValidationReport:
    """Held-out loss (the same texel-sigmoid MSE `train.py`'s training loop
    minimizes) and label correlation, over records the model was not trained on.
    """
    records = list(records)
    if not records:
        raise ValueError("evaluate_held_out requires at least one record")

    batch = encode_batch(records)
    target_cps = torch.tensor([target_cp(r.label) for r in records], dtype=torch.float32)
    targets = texel_sigmoid(target_cps, k)

    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)
        predicted_prob = texel_sigmoid(predicted_cp, k)
        loss = torch.mean((predicted_prob - targets) ** 2).item()
        correlation = _pearson_correlation(predicted_cp, target_cps)

    return ValidationReport(held_out_loss=loss, label_correlation=correlation, position_count=len(records))


def eval_scale_check(model: NnueNet, records: Iterable[ClassicalEvalRecord]) -> EvalScaleCheck:
    """Compares the trained net's raw centipawn output against a pre-computed
    classical-eval-labeled corpus (PRD "Trainer Requirements": the net's output
    must land on classical's calibrated centipawn scale, since search margins
    are tuned to that scale). See module docstring for the real corpus's status.
    """
    records = list(records)
    if not records:
        raise ValueError("eval_scale_check requires at least one record")

    batch = encode_fens(r.fen for r in records)
    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)

    classical_cps = torch.tensor([r.classical_eval_cp for r in records], dtype=torch.float32)
    mean_absolute_difference_cp = torch.mean(torch.abs(predicted_cp - classical_cps)).item()

    return EvalScaleCheck(
        mean_absolute_difference_cp=mean_absolute_difference_cp,
        position_count=len(records),
    )


@dataclass(frozen=True)
class AffineFit:
    """Least-squares fit of `target ≈ scale * predicted + shift` (issue #219 follow-up:
    can post-hoc affine recalibration correct the measured compression/bias without
    retraining?). Closed-form ordinary least squares, single predictor -- `scale` is
    `cov(predicted, target) / var(predicted)`, `shift` is the mean residual after
    centering. Passed into `calibration_report`'s `affine` parameter to evaluate the
    transformed output instead of the raw one."""

    scale: float
    shift: float


def fit_affine_calibration(model: NnueNet, records: Iterable[PositionRecord]) -> AffineFit:
    """Ordinary least squares fit of `target_cp ≈ scale * predicted_cp + shift` over
    `records`. Note this only zeroes signed mean error and pushes the compression ratio
    up to (not past) the predictor's correlation with the target -- a mathematical
    property of OLS, not a bug -- see the research doc for why that ceiling matters.
    """
    records = list(records)
    if not records:
        raise ValueError("fit_affine_calibration requires at least one record")

    batch = encode_batch(records)
    target_cps = torch.tensor([target_cp(r.label) for r in records], dtype=torch.float32)
    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)

    pred_mean, target_mean = predicted_cp.mean(), target_cps.mean()
    pred_centered, target_centered = predicted_cp - pred_mean, target_cps - target_mean
    variance = (pred_centered**2).mean()
    if variance.item() == 0:
        raise ValueError("fit_affine_calibration requires predicted_cp to have nonzero variance")
    scale = (pred_centered * target_centered).mean() / variance
    shift = target_mean - scale * pred_mean
    return AffineFit(scale=scale.item(), shift=shift.item())


@dataclass(frozen=True)
class CalibrationBucket:
    """Signed mean error and score-compression ratio (research doc §5.1) for one
    slice of held-out records. `compression_ratio` near 1 means the net's output
    spans a comparable cp range to the target; below 1 is compression, above 1 is
    expansion. `mae`/`rmse` are the usual error magnitudes, sign-discarding (unlike
    `signed_mean_error`). All four are `nan` for an empty bucket (nothing to divide by)."""

    signed_mean_error: float
    compression_ratio: float
    mae: float
    rmse: float
    position_count: int


@dataclass(frozen=True)
class CalibrationReport:
    """Issue #219: `evaluate_held_out`'s MAE/correlation say how loosely predictions
    track targets, not whether they're systematically biased. This is the additional,
    distinct calibration question — every bucket here is an aggregate over the same
    `predicted_cp`/`target_cp` arrays `evaluate_held_out` already computes, split per
    §5.1's mate-vs-cp and phase axes so a bias/compression effect specific to one
    slice isn't hidden by averaging across all of them."""

    overall: CalibrationBucket
    mate_labeled: CalibrationBucket
    cp_labeled: CalibrationBucket
    by_phase: dict[str, CalibrationBucket]


def calibration_report(
    model: NnueNet, records: Iterable[PositionRecord], affine: Optional[AffineFit] = None
) -> CalibrationReport:
    """Computes §5.1's calibration diagnostics against `records` (typically a
    held-out set). Does not touch `evaluate_held_out`'s own loss/correlation
    computation — this is an additional view over the same underlying predictions.

    `affine`, if given, is applied (`scale * predicted + shift`) before computing
    every bucket below — pass a `fit_affine_calibration` result to see what a
    post-hoc affine recalibration would do to these diagnostics, without touching
    the model or `output_scale` itself.
    """
    records = list(records)
    if not records:
        raise ValueError("calibration_report requires at least one record")

    batch = encode_batch(records)
    target_cps = torch.tensor([target_cp(r.label) for r in records], dtype=torch.float32)
    with torch.no_grad():
        predicted_cp = model(batch.us_indices, batch.us_offsets, batch.them_indices, batch.them_offsets)
    if affine is not None:
        predicted_cp = affine.scale * predicted_cp + affine.shift

    is_mate = torch.tensor([r.label.eval_mate is not None for r in records], dtype=torch.bool)
    phases = [phase_of(r.fen) for r in records]

    def bucket(mask: torch.Tensor) -> CalibrationBucket:
        count = int(mask.sum().item())
        if count == 0:
            return CalibrationBucket(
                signed_mean_error=float("nan"),
                compression_ratio=float("nan"),
                mae=float("nan"),
                rmse=float("nan"),
                position_count=0,
            )
        pred, targ = predicted_cp[mask], target_cps[mask]
        residual = pred - targ
        target_std = targ.std(unbiased=False).item()
        compression_ratio = pred.std(unbiased=False).item() / target_std if target_std != 0 else float("nan")
        return CalibrationBucket(
            signed_mean_error=residual.mean().item(),
            compression_ratio=compression_ratio,
            mae=residual.abs().mean().item(),
            rmse=torch.sqrt((residual**2).mean()).item(),
            position_count=count,
        )

    all_mask = torch.ones(len(records), dtype=torch.bool)
    by_phase = {
        phase: bucket(torch.tensor([p == phase for p in phases], dtype=torch.bool)) for phase in sorted(set(phases))
    }

    return CalibrationReport(
        overall=bucket(all_mask),
        mate_labeled=bucket(is_mate),
        cp_labeled=bucket(~is_mate),
        by_phase=by_phase,
    )


def _pearson_correlation(a: torch.Tensor, b: torch.Tensor) -> float:
    a = a.detach()
    b = b.detach()
    a_centered = a - a.mean()
    b_centered = b - b.mean()
    denominator = torch.sqrt((a_centered**2).sum() * (b_centered**2).sum())
    if denominator == 0:
        return 0.0
    return ((a_centered * b_centered).sum() / denominator).item()
